In [3]:
import numpy as np

In [4]:
mylist = [list(range(100,5000,1000))]

In [5]:
mylist

[[100, 1100, 2100, 3100, 4100]]

In [6]:
np.array(mylist)

array([[ 100, 1100, 2100, 3100, 4100]])

In [7]:
x =np.array(mylist)

In [8]:
x

array([[ 100, 1100, 2100, 3100, 4100]])

----

In [10]:
l2 = ["hello",52.3,22,True]

In [11]:
l2

['hello', 52.3, 22, True]

In [12]:
np.array(l2)

array(['hello', '52.3', '22', 'True'], dtype='<U32')

------

In [18]:
#Functions in array

In [14]:
x.sort()

In [15]:
x

array([[ 100, 1100, 2100, 3100, 4100]])

In [17]:
x.mean()

2100.0

-----

In [19]:
#Sclicing array

In [21]:
b = list(range(550,10000,1000))

In [22]:
b

[550, 1550, 2550, 3550, 4550, 5550, 6550, 7550, 8550, 9550]

In [23]:
np.array(b)

array([ 550, 1550, 2550, 3550, 4550, 5550, 6550, 7550, 8550, 9550])

In [28]:
list1 = list(range(500,600,10))

TypeError: 'range' object is not callable

In [25]:
list

range(500, 600, 10)

In [29]:
list1 = list(range(500,600,10))

TypeError: 'range' object is not callable

In [30]:
l3 = [range(500,600,10)]

In [31]:
l3

[range(500, 600, 10)]

In [32]:
l3 = list(range(500,600,10))

TypeError: 'range' object is not callable

In [33]:
clear

In [34]:
l3 = ["hello",52.3,22,True]

In [35]:
l3

['hello', 52.3, 22, True]

In [36]:
a = list(range(0:10:1))

SyntaxError: invalid syntax (4243782962.py, line 1)

In [38]:
list(range(10,100,10))

TypeError: 'range' object is not callable

In [39]:
import numpy as np

In [40]:
list(range(10,100,10))

TypeError: 'range' object is not callable

In [41]:
del range

NameError: name 'range' is not defined

In [42]:
b

[550, 1550, 2550, 3550, 4550, 5550, 6550, 7550, 8550, 9550]

In [43]:
type(b)

list

In [44]:
range(0,10)

range(0, 10)